INSERT INTO TESTS (ID, NAME, LENGTH, MAXPOINTS) VALUES ( 
1, 'Drivers test', 75, 18);

INSERT INTO QUESTIONS (ID, POINTS, CONTENT, ANSWER1, ANSWER2, ANSWER3, 
ANSWER4, ANSWER5) VALUES (0, 10, 'What is the first question?', 'abc_1', 'def_0', '', '', '');

INSERT INTO QUESTIONSIDS (TESTID, QUESTIONID) VALUES (1, 1);

INSERT INTO HISTORY (ID, TESTID, USERNAME, TIME, DURATION, SCORE) VALUES 
(0, 0, 'MAZAK', '2016-11-13 10:00:00', 5, 2);

INSERT INTO USERS (NAME, PASSWORD, TYPE) VALUES ('MAZAK', 'PASS', 1);

